export default [
  {
    id: 9791,
    sender: {
      name: 'Eva Přichystalová',
      email: 'eva.jochova@gmail.com',
    },
    subject: 'Podpis smlouvy',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '18.02.2022',
    time: '10:48',
    body: 'Fugit ullam suscipit aliquam? Pariatur cumque dolores consequuntur in mollitia, est vel sapiente officia cum velit excepturi praesentium totam beatae blanditiis possimus. Adipisci repellendus odit quia, neque unde consequatur totam.',
    unread: true,
  },
  {
    id: 9792,
    sender: {
      name: 'Martin Miksa',
      email: 'mikes.m@email.cz',
    },
    subject: 'Už to topí?',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '18.02.2022',
    time: '08:09',
    body: 'Doloremque provident saepe est facere animi eum ab unde sapiente, vitae laudantium, sint nam. Sint eos, libero perferendis quidem eveniet nihil sunt incidunt nobis. Earum, deserunt! Voluptas ipsa possimus iste?',
    unread: true,
  },
  {
    id: 9793,
    sender: {
      name: 'Marie Fodorová',
      email: 'marie.fodorova@zdravoteka.cz',
    },
    subject: 'Další dobrovolníci',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '18.02.2022',
    time: '08:51',
    body: 'Similique laudantium fugiat, rem cum doloribus minus quam, aliquid quia assumenda eum blanditiis maiores tenetur voluptates est, dolore dignissimos laboriosam incidunt neque doloremque dolores sapiente facilis magni vel recusandae! Nisi!',
    unread: true,
  },
  {
    id: 9794,
    sender: {
      name: 'Josef Kuneš',
      email: 'pepakunes@gmail.com',
    },
    subject: 'Kurz Komunikace I',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '17.02.2022',
    time: '17:18',
    body: 'Perferendis nulla adipisci distinctio tempora sed pariatur sunt aperiam nihil quae officia, rem, est, alias veritatis in omnis quis. Iusto magni quod eaque nam vel aspernatur illum ipsam! Repellat, est.',
    unread: true,
  },
  {
    id: 9795,
    sender: {
      name: 'Martin Miksa',
      email: 'mikes.m@email.cz',
    },
    subject: 'Opraváři na kotel',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '17.02.2022',
    time: '20:59',
    body: 'Nesciunt voluptas quas vitae asperiores exercitationem repellendus ipsam expedita, aliquid itaque perferendis nobis similique ab ex quisquam vero illo voluptates laudantium id rem ut officia omnis eveniet temporibus! Eum, amet?',
    unread: true,
  },
  {
    id: 9796,
    sender: {
      name: 'Romana Bilová',
      email: 'romanabilova@asap.com',
    },
    subject: 'Výsledek pracovního pohovoru',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '17.02.2022',
    time: '21:28',
    body: 'Ipsum vitae adipisci optio quo aliquam quia maiores explicabo consequuntur corporis labore distinctio aperiam fugiat neque consectetur, veritatis illo. Numquam quam veritatis animi fugit vel impedit qui molestiae minima excepturi!',
    unread: true,
  },
  {
    id: 9797,
    sender: {
      name: 'Marie Fodorová',
      email: 'marie.fodorova@zdravoteka.cz',
    },
    subject: 'Nábor dobrovolníků',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '16.02.2022',
    time: '18:11',
    body: 'Officia aut voluptates at nostrum delectus ducimus quod maxime quas vel. Amet atque necessitatibus dolor placeat reiciendis, pariatur, iusto dignissimos natus ipsam assumenda molestias recusandae optio magni. A, aut quibusdam?',
    unread: false,
  },
  {
    id: 9798,
    sender: {
      name: 'Marie Fodorová',
      email: 'marie.fodorova@zdravoteka.cz',
    },
    subject: 'Rozdělení příspěvků',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '16.02.2022',
    time: '17:44',
    body: 'Quasi quos necessitatibus, et aliquid fuga iusto quam minima distinctio ipsam veritatis praesentium vitae voluptates ipsa cum inventore facilis, architecto maiores quia delectus cumque rem. Sunt ipsa hic repellat laborum.',
    unread: false,
  },
  {
    id: 9799,
    sender: {
      name: 'Milan Nechvátal',
      email: 'nechvatalmilan@gmail.com',
    },
    subject: 'Přihláška na kurz',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '16.02.2022',
    time: '18:06',
    body: 'Recusandae cupiditate porro sint culpa in sunt soluta repudiandae officia architecto sapiente labore doloribus, sit nihil assumenda debitis maxime perspiciatis veritatis explicabo impedit. Exercitationem vero sequi aperiam maxime, at in?',
    unread: false,
  },
  {
    id: 9800,
    sender: {
      name: 'Jan Franěk',
      email: 'franek.j4@gmail.com',
    },
    subject: 'Přihláška na kurz',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '16.02.2022',
    time: '11:30',
    body: 'Alias assumenda accusantium totam natus! Eius aliquid est, placeat quod magnam ab porro ad praesentium doloribus natus minima maxime debitis vel facilis similique? Ipsa vitae esse consectetur tenetur perspiciatis velit.',
    unread: false,
  },
  {
    id: 9801,
    sender: {
      name: 'Romana Bilová',
      email: 'romanabilova@asap.com',
    },
    subject: 'Pracovní pohovor',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '15.02.2022',
    time: '20:14',
    body: 'Culpa tempora ea, fugiat officia aspernatur in porro. Harum delectus tenetur velit nesciunt est necessitatibus exercitationem accusamus, nam vitae adipisci natus modi omnis reprehenderit recusandae ex magni doloribus quae? Distinctio!',
    unread: false,
  },
  {
    id: 9802,
    sender: {
      name: 'Eva Přichystalová',
      email: 'eva.jochova@gmail.com',
    },
    subject: 'Finální nájmení smlouva',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '15.02.2022',
    time: '16:01',
    body: 'Illum, enim fugit porro alias suscipit eum maxime eveniet sit eligendi voluptates, debitis iusto omnis ullam. Voluptas natus, quibusdam eum commodi explicabo excepturi fuga, iusto minima vitae, doloribus praesentium nisi!',
    unread: false,
  },
  {
    id: 9803,
    sender: {
      name: 'Milan Nechvátal',
      email: 'nechvatil.milan@gmail.com',
    },
    subject: 'Třoška letní poezie',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '15.02.2022',
    time: '12:25',
    body: 'Ex inventore, quasi beatae expedita odio dolorem culpa asperiores ab iusto laboriosam deleniti nemo doloribus alias sequi! Vitae dolores distinctio repudiandae, impedit, laborum esse dicta itaque repellendus numquam necessitatibus officiis!',
    unread: false,
  },
  {
    id: 9804,
    sender: {
      name: 'Martin Miksa',
      email: 'mikes.m@email.cz',
    },
    subject: 'Nefunkční plynový kotel',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '15.02.2022',
    time: '19:30',
    body: 'Cumque, libero adipisci enim totam architecto impedit recusandae eveniet obcaecati molestiae amet quidem iusto illum, eaque qui autem laboriosam, iste at. Itaque cupiditate, et reiciendis magnam enim explicabo deleniti quibusdam!',
    unread: false,
  },
  {
    id: 9805,
    sender: {
      name: 'Eva Přichystalová',
      email: 'eva.jochova@gmail.com',
    },
    subject: 'Revize nájemní smlouvy',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '14.02.2022',
    time: '14:14',
    body: 'Doloremque vitae reiciendis consequatur sunt neque est incidunt, alias laborum aliquam excepturi expedita adipisci hic! Ipsam ducimus quia tempore. Quibusdam possimus soluta sapiente vero ipsum accusamus nisi cum architecto beatae!',
    unread: false,
  },
  {
    id: 9806,
    sender: {
      name: 'Jaruška Kozlovská',
      email: 'j.kozlovska@delivery.net',
    },
    subject: 'Nedoručená zásilka',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '14.02.2022',
    time: '21:33',
    body: 'Iste, ipsa perspiciatis voluptates voluptatibus pariatur iusto consectetur nostrum maiores culpa fugit dolorum. Culpa illo et, quos consectetur corrupti ipsa nulla! Reiciendis libero enim debitis tempora accusantium expedita architecto totam!',
    unread: false,
  },
  {
    id: 9807,
    sender: {
      name: 'Josef Kuneš',
      email: 'pepakunes@gmail.com',
    },
    subject: 'Sobotní výlet do lesů',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '13.02.2022',
    time: '09:11',
    body: 'Blanditiis soluta libero, dolorum totam labore alias animi! Deleniti vitae reiciendis iusto sequi voluptas, expedita, unde necessitatibus corrupti, esse id culpa odit excepturi amet. Laudantium sapiente voluptatibus hic vero dolorem.',
    unread: false,
  },
  {
    id: 9808,
    sender: {
      name: 'Marie Fodorová',
      email: 'marie.fodorova@zdravoteka.cz',
    },
    subject: 'Jóga pro těhotné',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '13.02.2022',
    time: '13:56',
    body: 'Ducimus odio minus neque itaque temporibus aliquid! Et amet a atque temporibus dolores, distinctio natus ipsum exercitationem molestias. Nostrum unde ipsum ut voluptate adipisci ipsam aspernatur quia temporibus excepturi? Quis.',
    unread: false,
  },
  {
    id: 9809,
    sender: {
      name: 'Zdeňka Nováková',
      email: 'zdenka.novakova@czechpress.cz',
    },
    subject: '',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '13.02.2022',
    time: '14:21',
    body: 'Illo dolore culpa tenetur veniam ad pariatur eum aperiam quidem praesentium nulla, nostrum commodi architecto, mollitia minima, quas sit! Dignissimos sit error sunt necessitatibus laboriosam dolorum aliquam nemo quasi? Aliquid!',
    unread: false,
  },
  {
    id: 9810,
    sender: {
      name: 'Alena Truncová',
      email: 'trunc.alenka@seznam.cz',
    },
    subject: '',
    recipient: 'bara.salajkova@daw-mail.com',
    date: '12.02.2022',
    time: '12:50',
    body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ipsum consectetur sequi pariatur inventore, fugit necessitatibus ullam repudiandae quam dolore aspernatur illo facere voluptatem iure totam, tempora dolor ex quaerat.',
    unread: false,
  },
];